cbow:
  left_window_size: 2
  right_window_size: 0
model:
  hidden_size: 2
  embedding_dim: 32
  hidden_dim: 16
  num_layers: 1
  fc_dim: 32
training:
  lr: 0.01
  batch_size: 4
  momentum: 0
  weight_decay: 0
  num_epochs: 5
  saves_folder: "saves"
data:
  path: "data/raw/wiki/people_wiki.csv"
  bruk_path: "data/raw/bruk"
  stopwords: "data/stopwords/stopwords_ua.txt"
  tokenizer_path: "data/processed/bruk/tokenizer.json"
  context_path: "data/processed/bruk/context.pt"
  target_path: "data/processed/bruk/target.pt"
  train_size: 750
  test_size: 56
  vocab_size: 100
  unk_token: "~"